# Generated by Django 2.1.3 on 2018-11-08 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('itens', '0001_initial'),
        ('users', '0003_auto_20181014_1220'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('description', models.TextField()),
                ('reward_xp', models.IntegerField()),
                ('reward_score', models.IntegerField()),
                ('url', models.URLField()),
                ('is_activated', models.BooleanField()),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.UserPlayer')),
                ('reward_iten', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='itens.Iten')),
            ],
        ),
    ]
