# Generated by Django 2.1.3 on 2018-11-13 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quests', '0002_auto_20181113_0321'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journal',
            name='status',
        ),
    ]
